server:
  port: 9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always